name: RAG Branch Build and Deploy

on:
  push:
    branches:
      - rag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bpawnzz/open-webui-mod1:rag-${{ github.sha }}
            ghcr.io/bpawnzz/open-webui-mod1:rag-latest
          build-args: |
            REPOSITORY_NAME=bpawnzz/open-webui-mod1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        with:
          tag_name: rag-${{ github.sha }}
          release_name: RAG Branch Release ${{ github.sha }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Check if release was created
        if: steps.create_release.outputs.id == ''
        run: echo "Release already exists, skipping creation"